# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-example-of-documentation
title: 量潮协作云
author: 量潮科技
description: 量潮协作云产品README文档
# Jupyter Book Config
only_build_toc_files: true